In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [3]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500


In [4]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
np.full(3,1.1)

array([1.1, 1.1, 1.1])

In [9]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [18]:
a=np.zeros((5,2))

In [19]:
a[0, 1]

np.float64(0.0)

In [22]:
c=np.array([[1,1,1],
           [2,2,2],
           [3,3,4]])

In [23]:
c[2,2]

np.int64(4)

In [24]:
c[2,2]=100
c

array([[  1,   1,   1],
       [  2,   2,   2],
       [  3,   3, 100]])

In [27]:
c[1]


array([2, 2, 2])

In [28]:
c[:,1]

array([1, 2, 3])

In [29]:
np.random.rand(5,2)

array([[0.32687041, 0.80957098],
       [0.41640053, 0.35574172],
       [0.15634574, 0.95591727],
       [0.3548399 , 0.30812306],
       [0.75430826, 0.24836861]])

In [30]:
np.random.seed(5)

In [31]:
100 * np.random.rand(5, 2)

array([[22.19931711, 87.07323062],
       [20.67191553, 91.86109079],
       [48.84111888, 61.17438629],
       [76.59078565, 51.84179879],
       [29.68005016, 18.77212287]])

In [34]:
np.random.randint(low=1, high=10, size=(3,2))

array([[6, 8],
       [1, 2],
       [5, 7]])

In [35]:
c>=2

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
a=np.array([[1,2,4,5,6]
,[90,22,3,6,9]])
b=np.random.seed(3)
b=np.random.randint(low=1,high=10,size=(2,5))


In [55]:
a>b

array([[False, False, False, False,  True],
       [ True,  True, False, False,  True]])

In [56]:
a[a>b]

array([ 6, 90, 22,  9])

NameError: name 'true' is not defined