In [2]:
import pandas as pd
import numpy as np

In [3]:
u=np.array([2,4,5,6])
2*u

array([ 4,  8, 10, 12])

In [4]:
v=np.array([1,0,0,2])
u+v

array([3, 4, 5, 8])

In [5]:
u*v

array([ 2,  0,  0, 12])

In [7]:
u.shape[0]

4

In [10]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n=u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i]*v[i]
    return result

In [11]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [12]:
u.dot(v)

np.int64(14)

In [13]:
U=np.array([[2,3,5,6],
            [1,2,1,2],
            [3,1,2,1]])
U.shape

(3, 4)

In [24]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows= U.shape[0]
    results= np.zeros(num_rows)
    for i in range(num_rows):
        results[i]= vector_vector_multiplication(U[i],v)
    return results

In [25]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [26]:
U.dot(v)

array([14,  5,  5])

In [27]:
V= np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])


In [33]:
def matrix_matrix_mul(U,V):
    assert U.shape[1]==V.shape[0]
    num_rows=U.shape[0]
    num_columns=V.shape[1]
    results = np.zeros((num_rows, num_columns))
    for i in range(num_columns):
        vi=V[:,i]
        Uvi=matrix_vector_multiplication(U,vi)
        results[:,i]=Uvi
    return results

In [34]:
matrix_matrix_mul(U,V)

array([[14. , 19.5, 12. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [35]:
U.dot(V)

array([[14. , 19.5, 12. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [36]:
I=np.eye(3)

In [37]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [39]:
Vs=V[[0,1,2]]

In [40]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [41]:
Vs_inv=np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])